CREATE TABLE Banks (
ID INT NOT NULL IDENTITY,
Name nvarchar(20) NOT NULL,

CONSTRAINT PK_Banks PRIMARY KEY (ID)
);

CREATE TABLE Towns (
ID INT NOT NULL IDENTITY,
Name nvarchar(30) NOT NULL,

CONSTRAINT PK_Towns PRIMARY KEY (ID)
);

CREATE TABLE Offices (
ID INT NOT NULL IDENTITY,
Address nvarchar(50) NOT NULL,
BankID INT NOT NULL,
TownID INT NOT NULL,

CONSTRAINT PK_Offices PRIMARY KEY (ID),
CONSTRAINT FK_BankID FOREIGN KEY (BankID) REFERENCES Banks(ID),
CONSTRAINT FK_TownID FOREIGN KEY (BankID) REFERENCES Towns(ID)
);

CREATE TABLE Statuses (
ID INT NOT NULL IDENTITY,
Name nvarchar(20) NOT NULL,

CONSTRAINT PK_Statuses PRIMARY KEY (ID)
);

CREATE TABLE Users (
ID INT NOT NULL IDENTITY,
Name nvarchar(30) NOT NULL,
StatusesID INT NOT NULL,

CONSTRAINT PK_Users PRIMARY KEY (ID),
CONSTRAINT FK_Statuses FOREIGN KEY (StatusesID) REFERENCES Statuses(ID)
);

CREATE TABLE Accounts (
UserID INT NOT NULL,
BankID INT NOT NULL,
Money DECIMAL(10,2) NOT NULL,

CONSTRAINT FK_Users FOREIGN KEY (UserID) REFERENCES Users(ID),
CONSTRAINT FK_Banks FOREIGN KEY (BankID) REFERENCES Banks(ID),
CONSTRAINT PK_Accounts PRIMARY KEY (UserID, BankID)
);

CREATE TABLE Cards (
ID INT NOT NULL IDENTITY,
UserID INT NOT NULL,
BankID INT NOT NULL,
Money DECIMAL(10,2) NOT NULL,

CONSTRAINT PK_Cards PRIMARY KEY (ID),
CONSTRAINT FK_Accounts FOREIGN KEY (UserID, BankID) REFERENCES Accounts(UserID, BankID)
);
